[package]
name = "first_native_program_solana"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib", "lib"]
[dependencies]
solana-program = "1.18.26"
borsh = "0.9.3"
borsh-derive = "0.9.1"
[dev-dependencies]
solana-program-test = "1.18.26"
solana-sdk = "1.18.26"
tokio = "1.42.0"
